// <auto-generated />
using GeMS_Key_Plus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeMS_Key_Plus.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200912152459_InitializeProject")]
    partial class InitializeProject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("GeMS_Key_Plus.Models.LinkButton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ButtonName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hotkey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireSplit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialDelimiters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Buttons");
                });
#pragma warning restore 612, 618
        }
    }
}
